---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tenant-helmrepo
  namespace: flux-system
spec:
  interval: 5m
  url: oci://ghcr.io/ams0/kubespaces-public/tenant:0.1.0