apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubespaces-public
  path: ./gitops/host/infrastructure/istio-ambient
  prune: false
  interval: 0m30s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubespaces-public
  path: ./gitops/host/infrastructure/cert-manager
  prune: false
  interval: 0m30s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubespaces-public
  path: ./gitops/host/infrastructure/external-dns
  prune: false
  interval: 0m30s