apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-api
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubespaces-public
  path: ./gitops/host/infrastructure/gateway-api
  prune: false
  interval: 0m30s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubespaces-public
  path: ./gitops/host/infrastructure/istio-ambient
  dependsOn:
    - name: gateway-api
  prune: false
  interval: 0m30s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubespaces-public
  path: ./gitops/host/infrastructure/cert-manager
  dependsOn:
    - name: istio
  prune: false
  interval: 0m30s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubespaces-public
  path: ./gitops/host/infrastructure/external-dns
  prune: false
  dependsOn:
    - name: cert-manager
  interval: 0m30s