apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: istio
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: kubespaces-public
  path: ./gitops/host/infrastructure/istio-ambient
  prune: true
  interval: 0m30s