apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-base
  namespace: flux-system
spec:
  chart:
    spec:
      chart: base
      version: 1.25.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  values:
    # Add any custom values here
